<a href="https://colab.research.google.com/github/AlexanderAmaya1/MAT-421-Homework/blob/main/Module_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module D: Linear Equations
Alexander Amaya

## 1.1: Introduction 

In [7]:
import numpy as np

# Learning how to use matricies in NumPy

a = np.matrix("1, 0; 0, 1")
print("Simple Identity Matrix: ")
print(a)
print('\n')


print("Simple Matrix B: ")

b = np.matrix("2, 2; 1, 1")
print(b)
print('\n')


print("Simple Matrix B Transposed: ")
print(b.transpose())


Simple Identity Matrix: 
[[1 0]
 [0 1]]


Simple Matrix B: 
[[2 2]
 [1 1]]


Simple Matrix B Transposed: 
[[2 1]
 [2 1]]


For this example, I familiarized myself with the NumPy Matrix functionality.

## 1.2: Elements of Linear Algebra

In [40]:
import numpy as np
from scipy import optimize

# Function to determine the eigen values and vectors for any 2x2 matrix where they exist
def eigen(a):

  f  = lambda x: ((a.tolist()[0][0]-x) * (a.tolist()[1][1]-x)) - (a.tolist()[0][1]*a.tolist()[1][0])
 
  eigen_values = []
  eigen_values.append(np.round_(optimize.fsolve(f,100))[0])   
  eigen_values.append(np.round_(optimize.fsolve(f,-100))[0]) 

  return eigen_values

# 1.2.4
# This demonstrates the use of the NumPy solution to calculate eigen values
b = np.matrix("2, 2; 1, 1")
print("Matrix B: ")
print(str(b)+'\n')


b_eigenvals = np.linalg.eig(b)

print("The Eigenvalues of Matrix B are: ")
print(b_eigenvals)
print("Using my custom function: ")
print(eigen(b))
print('\n')


Matrix B: 
[[2 2]
 [1 1]]

The Eigenvalues of Matrix B are: 
[3. 0.]
Using my custom function: 
[3.0, -0.0]


The Eigenvectors of Matrix B are: 
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In this examples I created a custom function that calculates the eigenvalues for any 2x2 matrix. The demo compares my results with the eig function in the NumPy Linear Algebra Library.

## 1.3: Linear Regression

In [127]:
import numpy as np

# QR Decomposition for any 3x3 matrix
def QR_decomp(a):
  u1 = a[0]
  e1 = u1 /(np.linalg.norm(u1))
 

  u2 = a[1] - np.vdot(a[1],e1)*e1
  
  e2 = u2 / (np.linalg.norm(u2))


  u3 = a[2] - ( np.vdot(a[2].A,e1.A) *e1) - (np.vdot(a[2].A,e2.A)*e2)

  e3 = u3 / (np.linalg.norm(u3))


  Q = np.matrix([   [e1.tolist()[0][0],e2.tolist()[0][0],e3.tolist()[0][0]],
                   
                    [e1.tolist()[0][1],e2.tolist()[0][1],e3.tolist()[0][1]],
                   
                    [e1.tolist()[0][2],e2.tolist()[0][2],e3.tolist()[0][2]]])

  R = np.matrix([ [np.vdot(a[0].A,e1.A), np.vdot(a[1].A,e1.A), np.vdot(a[2].A,e1.A)],
                  [0,                    np.vdot(a[1].A,e2.A), np.vdot(a[2].A,e2.A)],
                  [0,                    0,                    np.vdot(a[2].A,e3.A)]])

  return Q, R



a = np.matrix([[1, 1, 0] , [1,0,1],[0,1,1]])

print("Matrix A")
print(a)
print("\nQR Decomposition using NumPy Function")
print('\nQ:')
print(np.linalg.qr(a)[0])
print('\nR: ')
print(np.linalg.qr(a)[1])
print('\n')

print("QR Decomposition using my Custom Function")
Q,R = QR_decomp(a)
print('Q:')
print(Q)
print('\nR: ')
print(R)

Matrix A
[[1 1 0]
 [1 0 1]
 [0 1 1]]
QR Decomposition using NumPy Function

Q:
[[-0.70710678  0.40824829 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]
 [-0.          0.81649658  0.57735027]]

R: 
[[-1.41421356 -0.70710678 -0.70710678]
 [ 0.          1.22474487  0.40824829]
 [ 0.          0.          1.15470054]]


QR Decomposition using my Custom Function
Q:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]

R: 
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]


For this example I created a custom QR decomposition fucntion utilizing the Gram-Schmidt procedure.